In [1]:
import pandas as pd
import numpy as np
import datetime
import math

# Reading data

In [2]:
df_l = pd.read_csv('laliga-match-scores.csv', parse_dates = ['date'])
df_l.head()

,Unnamed: 0,day,date,time,home,xg_home,score,xg_away,away,attendance,venue,referee
0,0,Fri,2021-08-13,21:00,Valencia,1.3,1–0,1.2,Getafe,9868.0,Estadio de Mestalla,Jesús Gil
1,1,Sat,2021-08-14,19:30,Cádiz,0.4,1–1,1.0,Levante,6941.0,Estadio Nuevo Mirandilla,Santiago Jaime
2,2,Sat,2021-08-14,19:30,Mallorca,0.4,1–1,0.9,Betis,6279.0,Iberostar Estadi,Antonio Matéu Lahoz
3,3,Sat,2021-08-14,22:00,Osasuna,0.8,0–0,0.7,Espanyol,6715.0,Estadio El Sadar,Miguel Ángel Ortiz Arias
4,4,Sat,2021-08-14,22:00,Alavés,1.7,1–4,1.8,Real Madrid,3968.0,Estadio de Mendizorroza,César Soto

In [3]:
df_p = pd.read_csv('premierleague-match-scores.csv', parse_dates = ['date'])
df_p.head()

,Unnamed: 0,day,date,time,home,xg_home,score,xg_away,away,attendance,venue,referee
0,0,Fri,2021-08-13,20:00,Brentford,1.3,2–0,1.4,Arsenal,16479.0,Brentford Community Stadium,Michael Oliver
1,1,Sat,2021-08-14,12:30,Manchester Utd,1.5,5–1,0.6,Leeds United,72732.0,Old Trafford,Paul Tierney
2,2,Sat,2021-08-14,15:00,Watford,1.2,3–2,1.1,Aston Villa,20051.0,Vicarage Road Stadium,Mike Dean
3,3,Sat,2021-08-14,15:00,Chelsea,0.9,3–0,0.3,Crystal Palace,38965.0,Stamford Bridge,Jonathan Moss
4,4,Sat,2021-08-14,15:00,Everton,2.4,3–1,0.7,Southampton,38487.0,Goodison Park,Andy Madley

In [4]:
df_s = pd.read_csv('seriea-match-scores.csv', parse_dates = ['date'])
df_s.head()

,Unnamed: 0,day,date,time,home,xg_home,score,xg_away,away,attendance,venue,referee
0,0,Sat,2021-08-21,18:30,Hellas Verona,2.1,2–3,1.4,Sassuolo,5448.0,Stadio Marc'Antonio Bentegodi,Manuel Volpi
1,1,Sat,2021-08-21,18:30,Inter,1.5,4–0,1.0,Genoa,27402.0,Stadio Giuseppe Meazza,Valerio Marini
2,2,Sat,2021-08-21,20:45,Empoli,1.3,1–3,1.3,Lazio,3655.0,Stadio Carlo Castellani,Simone Sozza
3,3,Sat,2021-08-21,20:45,Torino,1.3,1–2,1.0,Atalanta,3475.0,Stadio Olimpico di Torino,Daniele Chiffi
4,4,Sun,2021-08-22,18:30,Bologna,1.5,3–2,1.6,Salernitana,8375.0,Stadio Renato Dall'Ara,Antonio Rapuano

# Data Cleaning

Removing Unnamed column.

In [5]:
df_l.drop(['Unnamed: 0', 'day', 'time'], axis = 1, inplace = True)
df_l.head()

,date,home,xg_home,score,xg_away,away,attendance,venue,referee
0,2021-08-13,Valencia,1.3,1–0,1.2,Getafe,9868.0,Estadio de Mestalla,Jesús Gil
1,2021-08-14,Cádiz,0.4,1–1,1.0,Levante,6941.0,Estadio Nuevo Mirandilla,Santiago Jaime
2,2021-08-14,Mallorca,0.4,1–1,0.9,Betis,6279.0,Iberostar Estadi,Antonio Matéu Lahoz
3,2021-08-14,Osasuna,0.8,0–0,0.7,Espanyol,6715.0,Estadio El Sadar,Miguel Ángel Ortiz Arias
4,2021-08-14,Alavés,1.7,1–4,1.8,Real Madrid,3968.0,Estadio de Mendizorroza,César Soto

In [6]:
df_p.drop(['Unnamed: 0', 'day', 'time'] , axis = 1, inplace = True)
df_p.head()

,date,home,xg_home,score,xg_away,away,attendance,venue,referee
0,2021-08-13,Brentford,1.3,2–0,1.4,Arsenal,16479.0,Brentford Community Stadium,Michael Oliver
1,2021-08-14,Manchester Utd,1.5,5–1,0.6,Leeds United,72732.0,Old Trafford,Paul Tierney
2,2021-08-14,Watford,1.2,3–2,1.1,Aston Villa,20051.0,Vicarage Road Stadium,Mike Dean
3,2021-08-14,Chelsea,0.9,3–0,0.3,Crystal Palace,38965.0,Stamford Bridge,Jonathan Moss
4,2021-08-14,Everton,2.4,3–1,0.7,Southampton,38487.0,Goodison Park,Andy Madley

In [7]:
df_s.drop(['Unnamed: 0', 'day', 'time'], axis = 1, inplace = True)
df_s.head()

,date,home,xg_home,score,xg_away,away,attendance,venue,referee
0,2021-08-21,Hellas Verona,2.1,2–3,1.4,Sassuolo,5448.0,Stadio Marc'Antonio Bentegodi,Manuel Volpi
1,2021-08-21,Inter,1.5,4–0,1.0,Genoa,27402.0,Stadio Giuseppe Meazza,Valerio Marini
2,2021-08-21,Empoli,1.3,1–3,1.3,Lazio,3655.0,Stadio Carlo Castellani,Simone Sozza
3,2021-08-21,Torino,1.3,1–2,1.0,Atalanta,3475.0,Stadio Olimpico di Torino,Daniele Chiffi
4,2021-08-22,Bologna,1.5,3–2,1.6,Salernitana,8375.0,Stadio Renato Dall'Ara,Antonio Rapuano

Check for NaN.

This function fills the attendance of a stadium with the average attendance only when the value is NaN for matches outside the Covid period.

In [8]:
def att_clean(s, att_map):
    for index, value in s.attendance.iteritems():
        if np.isnan(value) and not (datetime.datetime(2020, 4, 1) < s.date[index] < datetime.datetime(2021, 8, 1)):
            s.at[index, 'attendance'] = att_map.get(s.at[index, 'venue'])

In [9]:
l_att_map = df_l.groupby('venue').mean()['attendance'].apply(lambda x: x if np.isnan(x) else int(math.floor(x)) ).to_dict()

#that season rm had 0 attendance 
l_att_map['Estadio Alfredo Di Stéfano'] = 0
l_att_map

{'Camp Nou': 68250.0,
 'Coliseum Alfonso Pérez': 10203.0,
 'Estadi Municipal de Montilivi': 10686.0,
 'Estadio Alfredo Di Stéfano': 0,
 'Estadio Benito Villamarín': 45231.0,
 'Estadio Ciudad de Valencia': 18160.0,
 'Estadio El Alcoraz': 6604.0,
 'Estadio El Sadar': 16443.0,
 'Estadio La Rosaleda': 20333.0,
 'Estadio Manuel Martínez Valero': 15033.0,
 'Estadio Municipal José Zorrilla': 19339.0,
 'Estadio Municipal de Anoeta': 24460.0,
 'Estadio Municipal de Butarque': 10202.0,
 'Estadio Municipal de Ipurúa': 5359.0,
 'Estadio Municipal de Riazor': 20542.0,
 'Estadio Nuevo Los Cármenes': 14774.0,
 'Estadio Nuevo Mirandilla': 14055.0,
 'Estadio Ramón Sánchez Pizjuán': 33594.0,
 'Estadio San Mamés': 41470.0,
 'Estadio Santiago Bernabéu': 58349.0,
 'Estadio Wanda Metropolitano': 53306.0,
 'Estadio de Balaídos': 14958.0,
 'Estadio de Gran Canaria': 16183.0,
 'Estadio de Mendizorroza': 15860.0,
 'Estadio de Mestalla': 35693.0,
 'Estadio de la Cerámica': 15890.0,
 'Estadio del Rayo Vallecano': 9897.0,
 'Iberostar Estadi': 13581.0,
 'RCDE Stadium': 19241.0,
 'San Mamés': 37532.0}

In [10]:
att_clean(df_l, l_att_map)
df_l.isna().sum()

date            0
home            0
xg_home         0
score           0
xg_away         0
away            0
attendance    486
venue           0
referee         0
dtype: int64

Cleaning attendance for the Premier League.

In [11]:
p_att_map = df_p.groupby('venue').mean()['attendance'].apply(lambda x: x if np.isnan(x) else int(math.floor(x)) ).to_dict()
p_att_map

{'Anfield': 50543,
 'Bet365 Stadium': 29279,
 'Bramall Lane': 29251,
 'Brentford Community Stadium': 16917,
 'Cardiff City Stadium': 31407,
 'Carrow Road': 26916,
 'Craven Cottage': 22240,
 'Elland Road': 34892,
 'Emirates Stadium': 58311,
 'Etihad Stadium': 53076,
 'Goodison Park': 37870,
 'King Power Stadium': 31664,
 'Liberty Stadium': 20622,
 'London Stadium': 56837,
 'Molineux Stadium': 30564,
 'Old Trafford': 73024,
 'Selhurst Park': 24478,
 "St. James' Park": 50317,
 "St. Mary's Stadium": 29532,
 'Stamford Bridge': 38696,
 'The American Express Community Stadium': 29849,
 'The Hawthorns': 23562,
 "The John Smith's Stadium": 23621,
 'Tottenham Hotspur Stadium': 55281,
 'Turf Moor': 19956,
 'Vicarage Road Stadium': 20395,
 'Villa Park': 40712,
 'Vitality Stadium': 10565,
 'Wembley Stadium': 61169}

In [30]:
att_clean(df_p, p_att_map)
df_p.isna().sum()

date            0
home            0
xg_home         0
score           0
xg_away         0
away            0
attendance    440
venue           0
referee         0
g_home          0
g_away          0
result          0
dtype: int64

Cleaning attendance for the Serie A.

In [12]:
s_att_map = df_s.groupby('venue').mean()['attendance'].apply(lambda x: x if np.isnan(x) else int(math.floor(x)) ).to_dict()
s_att_map

{'Allianz Stadium': 33329,
 'Dacia Arena': 16550,
 'Sardegna Arena': 12886,
 'Stadio Alberto Picco': 6708,
 'Stadio Arechi': 15073,
 'Stadio Artemio Franchi': 26644,
 "Stadio Atleti Azzurri d'Italia": 15918,
 'Stadio Benito Stirpe': 13358,
 'Stadio Carlo Castellani': 7988,
 'Stadio Ciro Vigorito': 10672,
 'Stadio Città del Tricolore': 10443,
 'Stadio Comunale Luigi Ferraris': 17736,
 'Stadio Comunale Via Del Mare': 23295,
 'Stadio Dino Manuzzi': 1000,
 'Stadio Ennio Tardini': 14724,
 'Stadio Ezio Scida': 10298,
 'Stadio Giuseppe Meazza': 51374,
 "Stadio Marc'Antonio Bentegodi": 14087,
 'Stadio Mario Rigamonti': 14688,
 'Stadio Olimpico': 33961,
 'Stadio Olimpico di Torino': 16855,
 'Stadio Paolo Mazza': 13319,
 'Stadio Pierluigi Penzo': 6647,
 "Stadio Renato Dall'Ara": 19483,
 'Stadio San Paolo': 32057,
 "Stadio Sant'Elia": 14650}

In [13]:
att_clean(df_s, s_att_map)
df_s.isna().sum()

date            0
home            0
xg_home         0
score           0
xg_away         0
away            0
attendance    460
venue           0
referee         0
dtype: int64

Adding a goals column.

In [21]:
g_home = []
g_away = []

In [15]:
def score(s):
    g_home.append(int(s[0]))
    g_away.append(int(s[2]))
    return s
def score_clean(df):
    df.score.apply(score)

In [16]:
score_clean(df_l)
df_l['g_home'] = g_home
df_l['g_away'] = g_away
df_l.head()

,date,home,xg_home,score,xg_away,away,attendance,venue,referee,g_home,g_away
0,2021-08-13,Valencia,1.3,1–0,1.2,Getafe,9868.0,Estadio de Mestalla,Jesús Gil,1,0
1,2021-08-14,Cádiz,0.4,1–1,1.0,Levante,6941.0,Estadio Nuevo Mirandilla,Santiago Jaime,1,1
2,2021-08-14,Mallorca,0.4,1–1,0.9,Betis,6279.0,Iberostar Estadi,Antonio Matéu Lahoz,1,1
3,2021-08-14,Osasuna,0.8,0–0,0.7,Espanyol,6715.0,Estadio El Sadar,Miguel Ángel Ortiz Arias,0,0
4,2021-08-14,Alavés,1.7,1–4,1.8,Real Madrid,3968.0,Estadio de Mendizorroza,César Soto,1,4

In [20]:
score_clean(df_p)
df_p['g_home'] = g_home
df_p['g_away'] = g_away
df_p.head()

,date,home,xg_home,score,xg_away,away,attendance,venue,referee,g_home,g_away
0,2021-08-13,Brentford,1.3,2–0,1.4,Arsenal,16479.0,Brentford Community Stadium,Michael Oliver,2,0
1,2021-08-14,Manchester Utd,1.5,5–1,0.6,Leeds United,72732.0,Old Trafford,Paul Tierney,5,1
2,2021-08-14,Watford,1.2,3–2,1.1,Aston Villa,20051.0,Vicarage Road Stadium,Mike Dean,3,2
3,2021-08-14,Chelsea,0.9,3–0,0.3,Crystal Palace,38965.0,Stamford Bridge,Jonathan Moss,3,0
4,2021-08-14,Everton,2.4,3–1,0.7,Southampton,38487.0,Goodison Park,Andy Madley,3,1

In [22]:
score_clean(df_s)
df_s['g_home'] = g_home
df_s['g_away'] = g_away
df_s.head()

,date,home,xg_home,score,xg_away,away,attendance,venue,referee,g_home,g_away
0,2021-08-21,Hellas Verona,2.1,2–3,1.4,Sassuolo,5448.0,Stadio Marc'Antonio Bentegodi,Manuel Volpi,2,3
1,2021-08-21,Inter,1.5,4–0,1.0,Genoa,27402.0,Stadio Giuseppe Meazza,Valerio Marini,4,0
2,2021-08-21,Empoli,1.3,1–3,1.3,Lazio,3655.0,Stadio Carlo Castellani,Simone Sozza,1,3
3,2021-08-21,Torino,1.3,1–2,1.0,Atalanta,3475.0,Stadio Olimpico di Torino,Daniele Chiffi,1,2
4,2021-08-22,Bologna,1.5,3–2,1.6,Salernitana,8375.0,Stadio Renato Dall'Ara,Antonio Rapuano,3,2

Adding a results column.

In [23]:
def result(df):
    result = []
    for index in range(len(df)):
        if df['g_home'][index] > df['g_away'][index]:
            result.append(df['home'][index])
        elif df['g_home'][index] < df['g_away'][index]:
            result.append(df['away'][index])
        else:
            result.append('Draw')
    return result

In [24]:
df_l['result'] = result(df_l)
df_l.head()

,date,home,xg_home,score,xg_away,away,attendance,venue,referee,g_home,g_away,result
0,2021-08-13,Valencia,1.3,1–0,1.2,Getafe,9868.0,Estadio de Mestalla,Jesús Gil,1,0,Valencia
1,2021-08-14,Cádiz,0.4,1–1,1.0,Levante,6941.0,Estadio Nuevo Mirandilla,Santiago Jaime,1,1,Draw
2,2021-08-14,Mallorca,0.4,1–1,0.9,Betis,6279.0,Iberostar Estadi,Antonio Matéu Lahoz,1,1,Draw
3,2021-08-14,Osasuna,0.8,0–0,0.7,Espanyol,6715.0,Estadio El Sadar,Miguel Ángel Ortiz Arias,0,0,Draw
4,2021-08-14,Alavés,1.7,1–4,1.8,Real Madrid,3968.0,Estadio de Mendizorroza,César Soto,1,4,Real Madrid

In [25]:
df_p['result'] = result(df_p)
df_p.head()

,date,home,xg_home,score,xg_away,away,attendance,venue,referee,g_home,g_away,result
0,2021-08-13,Brentford,1.3,2–0,1.4,Arsenal,16479.0,Brentford Community Stadium,Michael Oliver,2,0,Brentford
1,2021-08-14,Manchester Utd,1.5,5–1,0.6,Leeds United,72732.0,Old Trafford,Paul Tierney,5,1,Manchester Utd
2,2021-08-14,Watford,1.2,3–2,1.1,Aston Villa,20051.0,Vicarage Road Stadium,Mike Dean,3,2,Watford
3,2021-08-14,Chelsea,0.9,3–0,0.3,Crystal Palace,38965.0,Stamford Bridge,Jonathan Moss,3,0,Chelsea
4,2021-08-14,Everton,2.4,3–1,0.7,Southampton,38487.0,Goodison Park,Andy Madley,3,1,Everton

In [26]:
df_s['result'] = result(df_s)
df_s.head()

,date,home,xg_home,score,xg_away,away,attendance,venue,referee,g_home,g_away,result
0,2021-08-21,Hellas Verona,2.1,2–3,1.4,Sassuolo,5448.0,Stadio Marc'Antonio Bentegodi,Manuel Volpi,2,3,Sassuolo
1,2021-08-21,Inter,1.5,4–0,1.0,Genoa,27402.0,Stadio Giuseppe Meazza,Valerio Marini,4,0,Inter
2,2021-08-21,Empoli,1.3,1–3,1.3,Lazio,3655.0,Stadio Carlo Castellani,Simone Sozza,1,3,Lazio
3,2021-08-21,Torino,1.3,1–2,1.0,Atalanta,3475.0,Stadio Olimpico di Torino,Daniele Chiffi,1,2,Atalanta
4,2021-08-22,Bologna,1.5,3–2,1.6,Salernitana,8375.0,Stadio Renato Dall'Ara,Antonio Rapuano,3,2,Bologna

# Win Stats

In [27]:
df_l.result.value_counts()

Draw               521
Barcelona          124
Real Madrid        120
Atlético Madrid    110
Sevilla             95
Betis               78
Real Sociedad       77
Villarreal          77
Valencia            72
Getafe              61
Athletic Club       61
Celta Vigo          56
Alavés              55
Levante             53
Eibar               42
Espanyol            41
Granada             37
Osasuna             36
Leganés             31
Valladolid          24
Girona              23
Elche               19
Cádiz               19
Mallorca            19
Rayo Vallecano      19
Huesca              14
La Coruña            6
Las Palmas           5
Málaga               5
Name: result, dtype: int64

In [28]:
df_p.result.value_counts()

Draw               433
Manchester City    146
Liverpool          131
Chelsea            102
Tottenham          102
Manchester Utd      99
Arsenal             94
Leicester City      79
West Ham            70
Everton             69
Newcastle Utd       60
Crystal Palace      59
Wolves              58
Burnley             57
Southampton         52
Brighton            48
Watford             39
Aston Villa         38
Bournemouth         33
Leeds United        27
Sheffield Utd       21
Brentford           13
Fulham              12
Huddersfield        12
West Brom           11
Norwich City        10
Cardiff City        10
Swansea City         8
Stoke City           7
Name: result, dtype: int64

In [29]:
df_s.result.value_counts()

Draw             470
Juventus         127
Napoli           118
Inter            117
Milan            106
Lazio            101
Atalanta          98
Roma              98
Sampdoria         68
Sassuolo          64
Fiorentina        64
Torino            60
Bologna           56
Udinese           56
Cagliari          47
Hellas Verona     44
Genoa             43
Parma             27
SPAL              24
Empoli            20
Spezia            19
Crotone           15
Benevento         13
Chievo            12
Lecce              9
Salernitana        7
Venezia            6
Brescia            6
Frosinone          5
Name: result, dtype: int64

In [31]:
df_p.head()

,date,home,xg_home,score,xg_away,away,attendance,venue,referee,g_home,g_away,result
0,2021-08-13,Brentford,1.3,2–0,1.4,Arsenal,16479.0,Brentford Community Stadium,Michael Oliver,2,0,Brentford
1,2021-08-14,Manchester Utd,1.5,5–1,0.6,Leeds United,72732.0,Old Trafford,Paul Tierney,5,1,Manchester Utd
2,2021-08-14,Watford,1.2,3–2,1.1,Aston Villa,20051.0,Vicarage Road Stadium,Mike Dean,3,2,Watford
3,2021-08-14,Chelsea,0.9,3–0,0.3,Crystal Palace,38965.0,Stamford Bridge,Jonathan Moss,3,0,Chelsea
4,2021-08-14,Everton,2.4,3–1,0.7,Southampton,38487.0,Goodison Park,Andy Madley,3,1,Everton

# Venue Stats

In [32]:
df_l.groupby('venue').mean()

,xg_home,xg_away,attendance,g_home,g_away
venue,,,,,
Camp Nou,2.122105,0.920000,68250.704225,2.494737,0.873684
Coliseum Alfonso Pérez,1.128421,0.868421,10203.704225,1.210526,0.778947
Estadi Municipal de Montilivi,1.276316,1.065789,10686.052632,1.131579,1.315789
Estadio Alfredo Di Stéfano,1.560000,0.808000,NaN,1.840000,0.600000
Estadio Benito Villamarín,1.413684,1.112632,45231.929577,1.631579,1.336842
Estadio Ciudad de Valencia,1.394737,1.362105,18160.357143,1.484211,1.484211
Estadio El Alcoraz,1.194737,1.123684,6604.631579,1.078947,1.342105
Estadio El Sadar,1.182456,1.152632,16443.515152,1.122807,1.368421
Estadio La Rosaleda,0.957895,1.205263,20333.000000,0.736842,1.421053
Estadio Manuel Martínez Valero,0.984211,1.478947,15033.900000,1.105263,1.157895
Estadio Municipal José Zorrilla,1.138596,1.129825,19339.593750,0.929825,1.245614
Estadio Municipal de Anoeta,1.550526,0.924211,24460.914286,1.610526,1.042105
Estadio Municipal de Butarque,1.089474,0.900000,10202.903846,0.964912,1.070175
Estadio Municipal de Ipurúa,1.298684,1.101316,5359.000000,1.236842,1.131579
Estadio Municipal de Riazor,1.652632,1.215789,20542.052632,1.157895,1.736842
Estadio Nuevo Los Cármenes,1.166667,1.219298,14774.906250,1.280702,1.228070
Estadio Nuevo Mirandilla,1.094737,1.410526,14055.210526,0.947368,1.421053
Estadio Ramón Sánchez Pizjuán,1.582105,0.958947,33594.757143,1.673684,0.884211
Estadio San Mamés,1.400000,2.100000,41470.666667,1.000000,1.666667
Estadio Santiago Bernabéu,2.045714,0.978571,58349.385714,2.242857,0.814286
Estadio Wanda Metropolitano,1.453684,0.800000,53306.464789,1.726316,0.589474
Estadio de Balaídos,1.366316,1.180000,14958.746479,1.505263,1.273684
Estadio de Gran Canaria,1.210526,1.536842,16183.105263,0.789474,2.000000
Estadio de Mendizorroza,1.157895,1.142105,15860.704225,1.031579,1.126316
Estadio de Mestalla,1.396842,1.076842,35693.736111,1.568421,0.957895
Estadio de la Cerámica,1.621053,1.116842,15890.112676,1.778947,1.200000
Estadio del Rayo Vallecano,1.347368,1.057895,9897.078947,1.342105,1.421053
Iberostar Estadi,1.218421,1.155263,13581.272727,1.184211,1.236842
RCDE Stadium,1.218421,1.186842,19241.971429,1.157895,1.157895
San Mamés,1.356522,0.868478,37532.208955,1.315217,0.880435

In [33]:
df_p.groupby('venue').mean()

,xg_home,xg_away,attendance,g_home,g_away
venue,,,,,
Anfield,2.210526,0.823158,50543.934211,2.421053,0.684211
Bet365 Stadium,1.105263,1.536842,29279.842105,1.052632,1.578947
Bramall Lane,1.134211,1.323684,29251.812500,0.947368,1.105263
Brentford Community Stadium,1.405263,1.047368,16917.894737,1.157895,1.105263
Cardiff City Stadium,1.226316,1.394737,31407.947368,1.105263,2.000000
Carrow Road,0.973684,1.781579,26916.242424,0.815789,2.105263
Craven Cottage,1.092105,1.389474,22240.523810,0.815789,1.684211
Elland Road,1.497368,1.552632,34892.750000,1.236842,1.552632
Emirates Stadium,1.755789,1.225263,58311.256757,2.010526,1.031579
Etihad Stadium,2.412632,0.722105,53076.887324,2.905263,0.747368
Goodison Park,1.332632,1.258947,37870.219178,1.400000,1.231579
King Power Stadium,1.474737,1.238947,31664.917808,1.600000,1.178947
Liberty Stadium,1.047368,1.342105,20622.631579,0.894737,1.263158
London Stadium,1.272632,1.278947,56837.630137,1.589474,1.410526
Molineux Stadium,1.259211,1.102632,30564.055556,1.263158,1.184211
Old Trafford,1.656842,0.997895,73024.054795,1.905263,1.063158
Selhurst Park,1.300000,1.144211,24478.364865,1.157895,1.252632
St. James' Park,1.189474,1.290526,50317.541667,1.231579,1.294737
St. Mary's Stadium,1.205263,1.256842,29532.297297,1.252632,1.473684
Stamford Bridge,1.793684,0.818947,38696.121622,1.757895,0.884211
The American Express Community Stadium,1.297895,1.138947,29849.931507,1.094737,1.315789
The Hawthorns,1.007895,1.502632,23562.450000,0.947368,1.789474
The John Smith's Stadium,0.842105,1.400000,23621.289474,0.684211,1.473684
Tottenham Hotspur Stadium,1.588710,1.116129,55281.275000,1.903226,0.951613
Turf Moor,1.161053,1.345263,19956.178082,1.010526,1.305263
Vicarage Road Stadium,1.225000,1.552632,20395.281690,1.210526,1.736842
Villa Park,1.287719,1.470175,40712.848485,1.403509,1.508772
Vitality Stadium,1.326316,1.368421,10565.903846,1.368421,1.491228
Wembley Stadium,1.815152,1.087879,61169.303030,1.969697,0.878788

In [34]:
df_s.groupby('venue').mean()

,xg_home,xg_away,attendance,g_home,g_away
venue,,,,,
Allianz Stadium,1.844211,0.834737,33329.222222,2.052632,0.736842
Dacia Arena,1.173684,1.214737,16550.082192,1.147368,1.294737
Sardegna Arena,1.200000,1.453947,12886.849057,1.276316,1.486842
Stadio Alberto Picco,1.168421,1.742105,6708.789474,1.105263,1.578947
Stadio Arechi,1.063158,1.605263,15073.263158,0.894737,2.052632
Stadio Artemio Franchi,1.537895,1.130526,26644.375000,1.442105,1.136842
Stadio Atleti Azzurri d'Italia,1.908602,1.020430,15918.144928,2.075269,1.193548
Stadio Benito Stirpe,1.022222,1.661111,13358.888889,0.777778,2.111111
Stadio Carlo Castellani,1.444737,1.852632,7988.157895,1.605263,1.947368
Stadio Ciro Vigorito,1.239474,1.834211,10672.681818,1.105263,2.078947
Stadio Città del Tricolore,1.480000,1.371579,10443.027397,1.536842,1.526316
Stadio Comunale Luigi Ferraris,1.296842,1.337895,17736.902098,1.373684,1.363158
Stadio Comunale Via Del Mare,1.447368,2.152632,23295.692308,1.578947,2.157895
Stadio Dino Manuzzi,1.347368,1.594737,1000.000000,1.473684,1.736842
Stadio Ennio Tardini,1.238983,1.525424,14724.405405,1.084746,1.576271
Stadio Ezio Scida,1.036842,1.528947,10298.750000,1.210526,1.578947
Stadio Giuseppe Meazza,1.791579,0.965789,51374.680556,1.847368,0.873684
Stadio Marc'Antonio Bentegodi,1.100000,1.302632,14087.688889,1.192982,1.482456
Stadio Mario Rigamonti,1.215789,1.936842,14688.307692,1.105263,1.789474
Stadio Olimpico,1.871579,1.134211,33961.493151,2.015789,1.142105
Stadio Olimpico di Torino,1.350000,1.317708,16855.541667,1.437500,1.291667
Stadio Paolo Mazza,1.119298,1.403509,13319.440000,1.017544,1.666667
Stadio Pierluigi Penzo,1.142105,1.915789,6647.736842,1.105263,2.000000
Stadio Renato Dall'Ara,1.247368,1.358947,19483.055556,1.431579,1.410526
Stadio San Paolo,1.904211,0.814737,32057.986111,2.126316,0.989474
Stadio Sant'Elia,1.247368,1.421053,14650.526316,0.947368,1.578947

# Referee Stats

In [37]:
df_l.referee.value_counts()

José Sánchez                101
Pablo González               98
Alberola Rojas               98
Carlos del Cerro             97
Jesús Gil                    96
Santiago Jaime               96
Ricardo de Burgos            95
Antonio Matéu Lahoz          95
Mario Melero                 93
Juan Martínez                91
Alejandro Hernández          90
Javier Estrada               80
José Luis Munuera            78
Adrián Cordero               75
Guillermo Cuadra             75
David Medié                  70
César Soto                   59
José González                58
Valentín Pizarro             54
Alberto Undiano              40
Ignacio Iglesias             39
Isidro Díaz de Mera          39
Eduardo Prieto               37
Jorge Figueroa               37
Alejandro Muñíz              19
José Munuera                 19
Daniel Trujillo              19
David Fernández              18
Miguel Ángel Ortiz Arias     17
Alfonso Álvarez              16
Xavi Estrada                  1
Name: referee, dtype: int64

In [36]:
df_p.referee.value_counts()

Anthony Taylor       147
Michael Oliver       146
Martin Atkinson      141
Mike Dean            132
Jonathan Moss        131
Andre Marriner       122
Craig Pawson         122
Kevin Friend         116
Paul Tierney         113
Chris Kavanagh       105
Stuart Attwell        99
Graham Scott          81
David Coote           69
Lee Mason             64
Simon Hooper          47
Andy Madley           46
Peter Bankes          39
Lee Probert           32
Roger East            28
Darren England        27
Robert Jones          22
Niel Swarbrick        20
Robert Madley         18
Mike Jones            12
Jarred Gillett         9
John Brooks            4
Tony Harrington        3
Michael Salisbury      3
Oliver Langford        1
Tim Robinson           1
Name: referee, dtype: int64

In [38]:
df_s.referee.value_counts()

Daniele Doveri       88
Maurizio Mariani     85
Davide Massa         85
Daniele Orsato       83
Marco Di Bello       81
                     ..
Daniel Amabile        1
Aleandro Di Paolo     1
Niccolò Baroni        1
Riccardo Pinzani      1
Lorenzo Illuzzi       1
Name: referee, Length: 61, dtype: int64

# Team Stats

In [57]:
def teamStats(team, df):
    team_df = df[(df.home == team) | (df.away == team)]
    results = team_df.result.apply(lambda x: x if ((x == team) | (x == 'Draw')) else 'Lose' )
    return results.value_counts().set_axis(['Win', 'Draw', 'Lose'])

In [58]:
teamStats('Liverpool', df_p)

Win     131
Draw     39
Lose     20
Name: result, dtype: int64

In [59]:
teamStats('Manchester City', df_p)

Win     146
Draw     24
Lose     20
Name: result, dtype: int64

In [60]:
teamStats('Manchester Utd', df_p)

Win     99
Draw    48
Lose    43
Name: result, dtype: int64

In [61]:
teamStats('Arsenal', df_p)

Win     94
Draw    59
Lose    37
Name: result, dtype: int64

In [68]:
def points(s, df):
    results = teamStats(s, df)
    return results[0] * 3 + results[1]

In [69]:
points('Liverpool', df_p)

432

In [70]:
points('Arsenal', df_p)

341

In [71]:
points('Manchester City', df_p)

462